CREATE TABLE customer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(50) NOT NULL COMMENT '客户姓名',
    phone VARCHAR(20) NOT NULL COMMENT '手机号码',
    level VARCHAR(10) NOT NULL DEFAULT '1' COMMENT '客户等级：1-普通客户，2-VIP客户，3-高级VIP客户',
    email VARCHAR(100) COMMENT '电子邮箱',
    address VARCHAR(255) COMMENT '联系地址',
    birthday DATE COMMENT '生日',
    points INT DEFAULT 0 COMMENT '积分',
    last_order_time DATETIME COMMENT '最近下单时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    UNIQUE KEY uk_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户表'; 